In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DJS Compute/DE Task 1/breast_cancer_survival - breast_cancer_survival_.csv.csv")

In [ ]:
df1 = df.copy()
df1.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.95256,2.15000,0.007972,-0.048340,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,20-May-18,26-Aug-18,Alive
1,54,FEMALE,0.00000,1.38020,-0.498030,-0.507320,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,26-Apr-18,25-Jan-19,Dead
2,63,FEMALE,-0.52303,1.76400,-0.370190,0.010815,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,24-Aug-18,08-Apr-20,Alive
3,78,FEMALE,-0.87618,0.12943,-0.370380,0.132190,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,16-Nov-18,28-Jul-20,Alive
4,42,FEMALE,0.22611,1.74910,-0.543970,-0.390210,II,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,12-Dec-18,05-Jan-19,Alive

In [ ]:
df1.shape

(334, 15)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 334 non-null    int64
 1   Gender              334 non-null    object
 2   Protein1            334 non-null    float64
 3   Protein2            334 non-null    float64
 4   Protein3            334 non-null    float64
 5   Protein4            334 non-null    float64
 6   Tumour_Stage        334 non-null    object
 7   Histology           334 non-null    object
 8   ER status           334 non-null    object
 9   PR status           334 non-null    object
 10  HER2 status         334 non-null    object
 11  Surgery_type        334 non-null    object
 12  Date_of_Surgery     334 non-null    object
 13  Date_of_Last_Visit  317 non-null    object
 14  Patient_Status      321 non-null    object
dtypes: float64(4), int64(1), object(10)
memory usage: 39.3+ KB

In [ ]:
df1.describe()

              Age    Protein1    Protein2    Protein3    Protein4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean    58.886228   -0.029991    0.946896   -0.090204    0.009819
std     12.961212    0.563588    0.911637    0.585175    0.629055
min     29.000000   -2.340900   -0.978730   -1.627400   -2.025500
25%     49.000000   -0.358888    0.362173   -0.513748   -0.377090
50%     58.000000    0.006129    0.992805   -0.173180    0.041768
75%     68.000000    0.343598    1.627900    0.278353    0.425630
max     90.000000    1.593600    3.402200    2.193400    1.629900

In [ ]:
df1.isnull().sum()

Age                    0
Gender                 0
Protein1               0
Protein2               0
Protein3               0
Protein4               0
Tumour_Stage           0
Histology              0
ER status              0
PR status              0
HER2 status            0
Surgery_type           0
Date_of_Surgery        0
Date_of_Last_Visit    17
Patient_Status        13
dtype: int64

In [ ]:
df1.duplicated().sum()

0

In [ ]:
percentage_missing = df1.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'percentage_missing': percentage_missing})
missing_value_df.head(15)

                    percentage_missing
Age                           0.000000
Gender                        0.000000
Protein1                      0.000000
Protein2                      0.000000
Protein3                      0.000000
Protein4                      0.000000
Tumour_Stage                  0.000000
Histology                     0.000000
ER status                     0.000000
PR status                     0.000000
HER2 status                   0.000000
Surgery_type                  0.000000
Date_of_Surgery               0.000000
Date_of_Last_Visit            5.089820
Patient_Status                3.892216

In [ ]:
df1.dropna(subset=['Date_of_Last_Visit','Patient_Status'], inplace = True)

In [ ]:
df1.shape

(317, 15)

In [ ]:
df1.isnull().sum()

Age                   0
Gender                0
Protein1              0
Protein2              0
Protein3              0
Protein4              0
Tumour_Stage          0
Histology             0
ER status             0
PR status             0
HER2 status           0
Surgery_type          0
Date_of_Surgery       0
Date_of_Last_Visit    0
Patient_Status        0
dtype: int64

In [ ]:
df1['Gender'].value_counts()

Gender
FEMALE    313
MALE        4
Name: count, dtype: int64

In [ ]:
df1['Gender'] = df1['Gender'].replace('MALE', 'FEMALE')

In [ ]:
df1['Tumour_Stage'].value_counts()

Tumour_Stage
II     180
III     77
I       60
Name: count, dtype: int64

In [ ]:
df1['Tumour_Stage'] = df1['Tumour_Stage'].replace({'I': 1, 'II': 2, 'III': 3})

In [ ]:
df1['ER status'].value_counts()

ER status
Positive    317
Name: count, dtype: int64

In [ ]:
df1['PR status'].value_counts()

PR status
Positive    317
Name: count, dtype: int64

In [ ]:
df1['HER2 status'].value_counts()

HER2 status
Negative    288
Positive     29
Name: count, dtype: int64

In [ ]:
df1['HER2 status'] = df1['HER2 status'].replace({'Negative': 0, 'Positive': 1})

In [ ]:
df1[['Day_of_Surgery', 'Month_of_Surgery', 'Year_of_Surgery']] = df1['Date_of_Surgery'].str.split('-', expand=True)

In [ ]:
df1[['Day_of_Last_Visit', 'Month_of_Last_Visit','Year_of_Last_Visit']] = df1['Date_of_Last_Visit'].str.split('-', expand=True)

In [ ]:
df1['Month_of_Surgery'] = df1['Month_of_Surgery'].replace({'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr':4, 'May':5, 'Jun':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12 })

In [ ]:
df1['Month_of_Last_Visit'] = df1['Month_of_Last_Visit'].replace({'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr':4, 'May':5, 'Jun':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12 })

In [ ]:
df1=df1.drop(columns=['Date_of_Surgery'],axis=1)
df1=df1.drop(columns=['Date_of_Last_Visit'],axis=1)

In [ ]:
df1.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Patient_Status,Day_of_Surgery,Month_of_Surgery,Year_of_Surgery,Day_of_Last_Visit,Month_of_Last_Visit,Year_of_Last_Visit
0,42,FEMALE,0.95256,2.15000,0.007972,-0.048340,2,Infiltrating Ductal Carcinoma,Positive,Positive,0,Other,Alive,20,5,18,26,8,18
1,54,FEMALE,0.00000,1.38020,-0.498030,-0.507320,2,Infiltrating Ductal Carcinoma,Positive,Positive,0,Other,Dead,26,4,18,25,1,19
2,63,FEMALE,-0.52303,1.76400,-0.370190,0.010815,2,Infiltrating Ductal Carcinoma,Positive,Positive,0,Lumpectomy,Alive,24,8,18,08,4,20
3,78,FEMALE,-0.87618,0.12943,-0.370380,0.132190,1,Infiltrating Ductal Carcinoma,Positive,Positive,0,Other,Alive,16,11,18,28,7,20
4,42,FEMALE,0.22611,1.74910,-0.543970,-0.390210,2,Infiltrating Ductal Carcinoma,Positive,Positive,1,Lumpectomy,Alive,12,12,18,05,1,19

In [ ]:
df1['Day_of_Surgery'] = df1['Day_of_Surgery'].astype(int)
df1['Year_of_Surgery'] = df1['Year_of_Surgery'].astype(int)
df1['Day_of_Last_Visit'] = df1['Day_of_Last_Visit'].astype(int)
df1['Year_of_Last_Visit'] = df1['Year_of_Last_Visit'].astype(int)